version: 1.5.7.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v143
    PLATFORM: ARM64
    PYTHON: "C:\\Python311-x64"

  - PlatformToolset: v143
    PLATFORM: x64
    PYTHON: "C:\\Python311-x64"

  - PlatformToolset: v143
    PLATFORM: Win32
    PYTHON: "C:\\Python311-x64"

configuration:
    - Release
    #- Debug

install:
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - python -m pip install -r requirements.txt

    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="ARM64" set archi=amd64_arm64
    - if "%platform%"=="ARM64" set platform_input=ARM64


    - if "%PlatformToolset%"=="v143" call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - call python validator.py %platform_input%
    - cd "%APPVEYOR_BUILD_FOLDER%"/vcxproj
    - msbuild nppPluginList.vcxproj /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin64\nppPluginList.dll" -FileName nppPluginList.dll
            Push-AppveyorArtifact "plugin_list_x64.md" -FileName plugin_list_x64.md
        }

        if ($env:PLATFORM_INPUT -eq "ARM64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "binarm64\nppPluginList.dll" -FileName nppPluginList.dll
            Push-AppveyorArtifact "plugin_list_arm64.md" -FileName plugin_list_arm64.md
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\nppPluginList.dll" -FileName nppPluginList.dll
            Push-AppveyorArtifact "plugin_list_x86.md" -FileName plugin_list_x86.md
        }
